### ISSUE TITLE
switch to stateless session resumption for nginx TLSv1.3 only configuration

### ISSUE THREAD

**Issue by thestinger** [mozilla/server-side-tls#282]
TLSv1.3 doesn't have session IDs or session tickets as their own features but rather only a generic session resumption system resembling tickets. Setting `ssl_session_tickets off` switches OpenSSL to using stateful TLSv1.3 resumption instead of stateless resumption. TLSv1.3 supports ECDHE session resumption and OpenSSL doesn't allow disabling it so it's always enabling no matter how people build it or configure it with another configuration file. That means it ALWAYS provides forward secrecy for resumed sessions for clients supporting it. In practice, no clients support only PSK without PSK + ECDHE resumption. Perhaps some weird embedded device. It would make a lot of sense to stop forcing stateful session caching for the TLSv1.3 only configuration.

The current approach of making a 10m shared memory region and using 1 day expiry is problematic because nginx will only purge 1 non-expired session in an attempt to free up room for a new session. However, the session state can vary in size and it's not uncommon to see errors logged (look in your error log) from this failing to free up room. If you have more than 40k sessions per 24h then your session cache is getting filled and you start seeing these errors. See https://trac.nginx.org/nginx/ticket/621 for details. You're making this mistake:

> with configurations assuming nginx will silently throw away old sessions if there will be not enough memory in the shared memory zone

Also worth noting: for TLSv1.2, stateful resumption doesn't resolve the forward secrecy issues from tickets not being automatically rotated. nginx does not actively purge expired sessions from the cache, so they sit there indefinitely until churn pushes them out. The best solution is using `ssl_session_ticket_key` and [doing your own rotation with a script](https://github.com/GrapheneOS/nginx-rotate-session-ticket-keys) but unfortunately that's beyond what the configuration generator can reasonably tell people to do. It's also easy for people to screw this up. They could have the rotation break or could end up doing their own approach not guaranteeing the files contain proper random keys at all times by not doing the rotation atomically, etc. I don't think nginx will be changing this because TLSv1.3 largely obsoletes the need to do it unless you need to synchronize across servers.

These 2 lines should be removed for the TLSv1.3 only configuration:

```nginx
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;
```

**Comment by thestinger** [comment]
Also see https://github.com/openssl/openssl/issues/13918 about it not being possible to disable ECDHE PSK session resumption with OpenSSL. The client would need to not support ECDHE PSK resumption, i.e. not a web browser but rather some weird embedded client, and I don't think people need to worry about that. nginx *does* rotate the tickets when configuration is reloaded so at minimum it gets rotated when people reload the configuration for any reason, which is quite frequent if you're doing OCSP stapling with an external cache to work around the built-in stapling not working reliably for multiple reasons (actually, will file another issue about something related to that).

**Comment by LeviPesin** [comment]
> Also worth noting: for TLSv1.2, stateful resumption doesn't resolve the forward secrecy issues from tickets not being automatically rotated. nginx does not actively purge expired sessions from the cache, so they sit there indefinitely until churn pushes them out.

As from https://github.com/mozilla/server-side-tls/issues/284, this seems to be fixed in NGINX 1.23.2.

**Comment by gstrauss** [comment]
ssl-config-generator no longer outputs `ssl_session_tickets off;` for nginx 1.23.2 or later.
(https://github.com/mozilla/ssl-config-generator/pull/252)

@thestinger do you still recommend removing `ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions` for TLSv1.3-only configurations?  Or has the issue with stateful session caching been fixed in nginx, too?  What version? 1.23.2?

**Comment by thestinger** [comment]
They partially fixed it but including `ssl_session_cache` still changes TLSv1.3 tickets from stateless to stateful. That artificially limits reuse to the number of sessions fitting inside the session cache. Since forward secrecy for tickets is always supported by the server for TLSv1.3 and used by all real world browsers, etc. I don't think it makes sense to keep using a stateful approach.

The stateful approach also isn't compatible with using the same rotated tickets across multiple instances which is very common, although that requires setting up using ticket files in noswap tmpfs and properly rotating/syncing them across instances so it doesn't particularly matter if the default config is incompatible with it when a lot more is required.

The way they implemented ticket rotation unfortunately means that it won't happen without `ssl_session_cache` enabled which is quite a strange approach since it changes how TLSv1.3 tickets work to stateful. I don't really know what should be recommended in case people start with the TLSv1.3 configuration and then enable TLSv1.2, where they wouldn't have rotation without the shared memory region configured. nginx didn't do a good job of providing proper configuration for this.

**Comment by gstrauss** [comment]
@thestinger thanks.  I think for TLSv1.3-only, I will add `ssl_session_cache` *commented out* with a comment above it stating that it should be enabled if TLSv1.2 is enabled in `ssl_protocols`

The historical reason that ssl-config-generator recommended `ssl_session_tickets off;` was precisely because of no proper session ticket encryption key (STEK) rotation.  By default, openssl does not rotate the session ticket encryption key (STEK), and as you pointed out, coordination between multiple servers and multiple machines requires more complicated setups.  

For simpler configs (single server), I have advocated for enabling session tickets *and* recommending that the server be restarted daily to cause openssl to generate a new session ticket encryption key.

**Comment by thestinger** [comment]
> that the server be restarted daily

Reloading the configuration did rotate the tickets even before the new rotation implementation.

It's still likely better to configure it via noswap tmpfs and a script since otherwise it'll invalidate tickets after the configuration is reloaded twice instead of making sure they last for the amount of time advertised to clients. They really didn't do a great job with this stuff. We're still using the session ticket key file feature with 4 ticket keys in noswap tmpfs with a script rotating them to have them last for at least a minimum amount of time that's configured to be the session key lifetime sent to clients, which is the same configuration setting for setting the lifetime of stateful sessions.

**Comment by gstrauss** [comment]
That really is a mess.  When I wrote session ticket encryption key rotation in lighttpd (in 2020, 2 years before nginx 1.23.2), I tried to document some of the scenarios https://wiki.lighttpd.net/Docs_SSL#Session-Tickets

There are challenges (extra steps an admin has to take) to securely synchronize a session ticket encryption key between multiple processes and multiple servers, and I think most of that complexity is outside the scope of ssl-config-generator guidelines.  Where possible, I still want to warn people about known pitfalls of doing something wrong, so I thank you for your input and will try to incorporate what I can (though without writing paragraphs of comments in the middle of the configs!)

**Comment by gstrauss** [comment]
As above, I added a commented-out `ssl_session_cache` with comment to enable if TLSv1.2 is added to `ssl_protocols`.
Please review https://ssl-config.mozilla.org/#server=nginx and let me know if you have any comments, or if this issue can be closed.  Thank you.

**Comment by gene1wood** [comment]
Closing issue at request of @gstrauss.
Please comment if you think issue should be reopened.
